os: windows

language: shell

script:
  - dir
  - echo %PATH%
  - set PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - echo %PATH%
  - choco install python3 --version 3.8.0
  - python --version
  - python -m pip install --upgrade pip
  - echo %PATH%
  - set PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - echo %PATH%
  - python program.py
