os: windows

language: shell

script:
  - dir
  - choco install python3
  - python --version
  - python -m pip install --upgrade pip
  - PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - python program.py
